backpacking_blueprint/urls.py
from django.contrib import admin
from django.urls import path, include

# Serving Static files during development
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('favicon.ico', RedirectView.as_view(url=settings.STATIC_URL + 'favicon.ico')),
    
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name = 'home'),
    path('accounts/signin/', views.Signin.as_view(), name='signin'),
    path('accounts/signup/', views.signup, name='signup'),
    
    path('discover/', views.discover, name="discover"),
    path('dashboard/', views.dashboard, name="dashboard"), 
    
    # TRAIL
    path('trails/', views.trail_index, name="trail-index"),
    # path('trails/archive/', views.trail_archive, name="trail-archive"),
    path('trails/<int:trail_id>/', views.trail_detail, name="trail-detail"),
    path('trails/create/', views.TrailCreate.as_view(), name="trail-create"),
    path('trails/<int:pk>/update/', views.TrailUpdate.as_view(), name='trail-update'),
    path('trails/<int:pk>/delete/', views.TrailDelete.as_view(), name='trail-delete'),
    
    
    # DAY
    path('days/<int:day_id>/', views.day_detail, name="day-detail"), 
    path('days/<int:pk>/update/', views.DayUpdate.as_view(), name ="update-day"),
    
    # GEAR
    path('gear/', views.gear_index, name='gear-index'),
    path('gear/create/', views.GearCreate.as_view(), name='gear-create'),
    path('gear/<int:pk>/update/', views.GearUpdate.as_view(), name='gear-update'),
    # path('gear/<int:pk>/packed/', views.packed_gear, name='packed'),
    path('gear/<int:pk>/delete/', views.GearDelete.as_view(), name='gear-delete'),
    
    # M:M TRAIL:GEAR
    path('trails/<int:trail_id>/associate-gear/', views.available_gear, name='available-gear-index'), 
    path('trails/<int:trail_id>/gear-details/', views.trail_gear_details, name='trail-gear-details'), 
    path('trails/<int:trail_id>/associate-gear/<int:gear_id>/', views.associate_gear, name='associate-gear'),
    path('trails/<int:trail_id>/remove-gear/<int:gear_id>/', views.remove_gear, name='remove-gear'), 
    
    #FOOD
    path('food/', views.food_index, name="food-index"), 
    path('food/create/', views.FoodCreate.as_view(), name='food-create'), 
    path('food/<int:pk>/update', views.FoodUpdate.as_view(), name='food-update'), 
    path('food/<int:pk>/delete', views.FoodDelete.as_view(), name='food-delete'),
    
    # M:M DAY:MEALS
    path('trails/<int:trail_id>/mealplan', views.meal_plan, name='meal-plan'),
    path('days/<int:day_id>/mealplan', views.available_food, name='available-food'),
    path('days/<int:day_id>/add-food/<int:food_id>/', views.add_food, name='add-food'), 
    path('days/<int:day_id>/remove-food/<int:food_id>/', views.remove_food, name='remove-food'), 

    # O:M DAY:NOTES
    path('days/<int:day_id>/add-note', views.add_note, name='add-note'),
    path('days/<int:day_id>/delete-note/<int:note_id>/', views.note_delete, name='note-delete'), 
]

main_app/models.py
from django.db import models
from django.conf import settings
import geocoder
from django.urls import reverse
from django.db.models.functions import Lower
from django.utils import timezone
from datetime import timedelta
from django.db.models import Sum
from decimal import Decimal
from collections import defaultdict
from django.contrib.auth.models import User

category_choices = (
    ('big_three', 'Big Three (Backpack, Tent, Sleeping Bag)'),
    ('water', 'Water'),
    ('food', 'Food Storage'),
    ('cooking', 'Cooking & Utensils'),
    ('clothing', 'Clothing & Footwear'),
    ('toiletries', 'Toiletries'),
    ('tools', 'Tools'),
    ('saftey', 'Saftey'),
    ('electronics', 'Electronics'),
    ('entertainment', 'Entertainment'),
)

weight_choices = (
    ('oz', 'oz'),
    ('lb', 'lb'),
)

meal_category = (
    ('breakfast', 'Breakfast'),
    ('lunch', 'Lunch'),
    ('snack', 'Snack'),
    ('dinner', 'Dinner'),
    ('drinks', 'Drinks'),
)

cover_image_choices = (
    ('cover_image_1.jpg', 'Image 1'),
    ('cover_image_2.jpg', 'Image 2'),
    ('cover_image_3.jpg', 'Image 3'),
    ('cover_image_4.jpg', 'Image 4'),
    ('cover_image_5.jpg', 'Image 5'),
    ('cover_image_6.jpg', 'Image 6'),
    ('cover_image_7.jpg', 'Image 7'),
    ('cover_image_8.jpg', 'Image 8'),
    ('cover_image_10.jpg', 'Image 10'),
)

# Create your models here.
class Gear(models.Model):
    category = models.CharField(('Category* '), max_length=20, choices=category_choices)
    name = models.CharField(("Item name* "), max_length=200)
    brand = models.CharField(max_length=200, blank=True, null=True)
    link = models.URLField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    own = models.BooleanField(default=False)
    weight = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    weight_m = models.CharField(("Weight Measurment"), max_length=2, choices=weight_choices, blank=True, null=True)
    packed = models.BooleanField(default=False)
    # is_suggested = models.BooleanField(default=False)

    weight_lb = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    
    # foreign key linking to a user instance
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def save(self, *args, **kwargs):
        if self.weight and self.weight_m :
            if self.weight_m == 'oz':
                self.weight_lb = self.weight * Decimal('0.0625')
            else:
                self.weight_lb = self.weight
                
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = [Lower('name')]
        

class Trail(models.Model):
    name = models.CharField(('Adventure Name* '),max_length=200)
    start_date = models.DateField('Start Date* ')
    end_date = models.DateField('End Date* ')
    location_name = models.CharField(('Name'), max_length=200, blank=True, null=True)
    location = models.CharField(('Address'), max_length=200, blank=True, null=True)
    distance = models.DecimalField( ('Distance (mi)'), max_digits=10, decimal_places=2,  blank=True, null=True)
    elevation = models.DecimalField(('Elevation Gain (ft)'), max_digits=10, decimal_places=2,  blank=True, null=True)
    duration = models.DurationField(blank=True, null=True)
    # image = models.ImageField(('Cover Image'), upload_to='cover_image/', default='cover_image_1.jpg', blank=True, null=True)
    image = models.CharField(('Cover Image* '), max_length=100, choices=cover_image_choices)
    
    # foreign key linking to a user instance
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    # MAP FEATURE
    lat = models.FloatField(blank=True, null=True)
    long = models.FloatField(blank=True, null=True)
    
    
    # when the instance is saved convert the location into lat/long
    def save(self, *args, **kwargs):
        if self.location:
            # API call
            g = geocoder.mapbox(self.location, key=settings.MAPBOX_ACCESS_TOKEN)
            # return the lat/long of the location in a list
            g = g.latlng
            # assign lat/long to model
            self.lat = g[0]
            self.long = g[1]

    # automatically calculate and save the duration based on the date inputs before submitting
        if self.start_date and self.end_date:
            self.duration = self.end_date - self.start_date + timedelta(days=1)
            
        super().save(*args, **kwargs)
    
    # when instance is deleted, delete image file
    # def delete(self):
    #     self.image.delete()
    #     super().delete()
        
    class Meta:
        ordering = ['start_date']
        
    # M:M relationship with Gear
    gear = models.ManyToManyField(Gear)
    
    def total_weight(self):
        return sum(gear.weight_lb for gear in self.gear.all() if gear.weight_lb)
    
    # defaultdict(float) initializes each new category with a default value of 0.0
    def weight_by_category(self):
        category_totals = defaultdict(float)
        for gear in self.gear.all():
            if gear.weight_lb:
                category_totals[gear.category] += float(gear.weight_lb)
        return dict(category_totals)
    
    def __str__(self):
        return self.name
    
    # method to get the url for this particular instance
    def get_absolute_url(self):
        return reverse("trail-detail", kwargs={"trail_id": self.id})

class Food(models.Model):
    name = models.CharField(('Name* '),max_length=200)
    calories = models.IntegerField(blank=True, null=True)
    weight = models.DecimalField(("Weight (grams)"), max_digits=10, decimal_places=2, default=Decimal('0.00'), blank=True, null=True)
    # category = models.CharField(max_length=20, choices=meal_category, blank=True, null=True)
    
    def __str__(self):
        return self.name
    
    # foreign key linking to a user instance
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        ordering = [Lower('name')]
    
class Day(models.Model): 
    day = models.IntegerField()
    date = models.DateField()
    start_campsite = models.CharField(('Name'),max_length=200, blank=True, null=True)
    finish_campsite = models.CharField(('Name'),max_length=200, blank=True, null=True)
    start_location = models.CharField(('Address'), max_length=200, blank=True, null=True)
    finish_location = models.CharField(('Address'), max_length=200, blank=True, null=True)
    distance = models.DecimalField(('Distance (mi)'), max_digits=10, decimal_places=2,  blank=True, null=True)
    elevation = models.DecimalField(('Elevation Gain (ft)'), max_digits=10, decimal_places=2,  blank=True, null=True)
    # notes = models.TextField(max_length=250, blank=True, null=True)
    
    # MAP FEATURE
    start_lat = models.FloatField(blank=True, null=True)
    start_long = models.FloatField(blank=True, null=True)
    
    finish_lat = models.FloatField(blank=True, null=True)
    finish_long = models.FloatField(blank=True, null=True)
    
    def save(self, *args, **kwargs):
        if self.start_location:
            g = geocoder.mapbox(self.start_location, key=settings.MAPBOX_ACCESS_TOKEN)
            g = g.latlng
            self.start_lat = g[0]
            self.start_long = g[1]
            
        if self.finish_location:
            g = geocoder.mapbox(self.finish_location, key=settings.MAPBOX_ACCESS_TOKEN)
            g = g.latlng
            self.finish_lat = g[0]
            self.finish_long = g[1]
            
        super().save(*args, **kwargs)

    # relationships
    trail = models.ForeignKey(Trail, on_delete=models.CASCADE)
    food = models.ManyToManyField(Food)
    
    def total_calories(self):
        return sum(food.calories for food in self.food.all())
    
    def total_weight_g(self):
        return sum(food.weight for food in self.food.all())
    
    def total_weight_lb(self):
        return self.total_weight_g() * Decimal(0.00220462)
    
    def __str__(self):
        return f"Day {self.day} on {self.date}"
    
    class Meta:
        ordering = ['date']
        
    def get_absolute_url(self):
        return reverse("day-detail", kwargs={"day_id": self.id})
    
class Note(models.Model):
    note = models.TextField(max_length=250)
    created = models.DateField(auto_now_add=True)
    
    # Trail Foreign Key
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    # foreign key linking to a user instance
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['created']
    
    def __str__(self):
        return f'Note created on {self.created}'

main_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from .models import Trail, Note, User

class TrailForm(forms.ModelForm):
    class Meta:
        model = Trail
        fields = ['name', 'start_date', 'end_date', 'location_name', 'location', 'distance', 'elevation', 'image']
        widgets = {
            'start_date' : forms.DateInput(
                format=('%Y-%m-%d'),
                attrs= {
                    'placeholder': "Select a date",
                    'type': 'text',
                    'id' : 'start-date'
                }
            ),
            'end_date' : forms.DateInput(
                format=('%Y-%m-%d'),
                attrs= {
                    'placeholder': "Select a date",
                    'type': 'text',
                    'id' : 'end-date'
                }
            ),
            
            'image': forms.RadioSelect(attrs={
                'class': 'custom-radio'
            })
        }
        
    def clean(self):
        cleaned_data = super().clean()
        start = cleaned_data.get('start_date')
        end = cleaned_data.get('end_date')
        
        if start and end and end < start:
            self.add_error('end_date', 'End date cannot be before start date')
        
        
class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['note']
        
class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
    
    # need to 
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        
class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # set placeholders
        self.fields['username'].widget.attrs.update({
            'placeholder': 'Username',
            'autofocus': True,
        })
        self.fields['password'].widget.attrs.update({
            'placeholder': 'Password',
        })

main_app/templates/trails/archive.html
{% extends "base.html" %} {% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "css/trails/trail-index.css" %}">
{% endblock head %}

{% block content %}
<div>
    <section class="page-header">
        <div class="links">
            <h1 >Archive</h1>
            <a href="{% url "trail-index" %}">Upcoming</a>
            <li><a href="{% url "trail-create" %}">Add New Adventures</a></li>
        </div>

    </section>

    <section class="card-container">
        {% if past_trails.count %}

            {% for trail in past_trails %}
                <div class="card">
                    <a href="{% url "trail-detail" trail.id %}">

                        <div class="card-content">
                            <div class="card-img-container">
                                <img src="{% static "images/" %}{{trail.image}}" alt="{{trail.name}}">
                            </div>
                            <div class="card-details">
                                <h2 class="card-title">{{trail.name}}</h2>
                                <p>{{trail.start_date}} ➤ {{trail.end_date}}</p>
                            </div>
                        </div>

                    </a>
                    
                </div>

            {% endfor %}
        {% else %}
        <p>Oh the places you have been!</p>
        {% endif %}
        
    </section>
</div>

{% endblock content %}

main_app/templates/trails/detail.html
{% extends "base.html" %} {% load static %}
{% block head %}
<link rel="stylesheet" href="{% static "css/trails/trail-detail.css" %}">

    <script src='https://api.mapbox.com/mapbox-gl-js/v3.12.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v3.12.0/mapbox-gl.css' rel='stylesheet' />
{% endblock head %}

{% block content %}
<div class="container">
    <div class="grid-container">

        <div class="img-container top" style="background-image: url('{% static "images/" %}{{trail.image}}');">
            <div class="img-header">
                <h5 class="success">Hi {{user.username}}</h5>
                <h3 class="success">Welcome To Your {{trail.name}} Adventure!</h3>
                <h5 class="success">{{trail.start_date}} - {{trail.end_date}}</h5>
            </div>
        </div>


        <div class="details-container top">
            <h4>Trail Details:</h4>
            {% if trail.location_name %}
            <h5>Starting Location: {{trail.location_name}}</h5>
            {% endif %}

            {% if trail.distance %}
            <h5>Distance: {{trail.distance}} miles</h5>
            {% endif %}
            
            {% if trail.elevation %}
            <h5>Elevation: {{trail.elevation}} ft</h5>
            {% endif %}
            
            <h5>Duration: {{trail.duration.days}} days</h5>
        </div>

        <div class="action-links-container top">
            <div class="form-action-links">
                <a href="{% url "trail-update" trail.id%}" class=""><h5>Edit</h5></a>
                <a href="{% url "trail-delete" trail.id%}" class=""><h5>Delete</h5></a>
            </div>

            <a href="{% url "trail-gear-details" trail.id%}" class="btn-warning primary "><h5>Gear Details</h5></a>
            <a href="{% url "meal-plan" trail.id%}" class="btn-warning primary"><h5>Meal Plan</h5></a>
        </div>


        <div class="map-container">
            <div id='map'></div>
            <script>
                mapboxgl.accessToken = '{{ mapbox_access_token }}';
                
                const map = new mapboxgl.Map({
                    container: 'map', // container ID
                    style: 'mapbox://styles/mapbox/outdoors-v12', // style URL
                    {% if trail.lat and trail.long %}
                        center: [{{trail.long}}, {{trail.lat}}], // starting position [lng, lat]
                    {% else %}
                        center: [-110.4, 44.5], //Yellowstone National Park
                    {% endif %}
                    zoom: 5, // starting zoom
                });

                const nav = new mapboxgl.NavigationControl();
                map.addControl(nav);

                var marker = new mapboxgl.Marker()
                        .setLngLat([ {{trail.long}}, {{trail.lat}} ])
                        .setPopup(new mapboxgl.Popup().setHTML('<h5> {{trail.location}} </h5>'))
                        .addTo(map);

                {% for day in trail.day_set.all %}
                    {% if day.start_lat and day.start_long %}
                        marker = new mapboxgl.Marker({color: "green"})
                            .setLngLat([ {{day.start_long}}, {{day.start_lat}} ])
                            .setPopup(new mapboxgl.Popup().setHTML('<h5> Day {{day.day}} Start: {{day.start_location}} </h5>'))
                            .addTo(map);
                    {%endif%}

                    {% if day.finish_lat and day.finish_long %}
                        marker = new mapboxgl.Marker({color: "red"})
                            .setLngLat([ {{day.finish_long}}, {{day.finish_lat}} ])
                            .setPopup(new mapboxgl.Popup().setHTML('<h5> Day {{day.day}} Finish: {{day.finish_location}} </h5>'))
                            .addTo(map);
                    {%endif%}

                {% endfor %}

                
            </script>
        </div>

        <div class="feature-container">
            <div class="subsection-title">
                <h2 class="subsection-title-text">Itinerary</h2>
            </div>

            {% for day in trail.day_set.all %}
            <div class="day-container">
                
                    <a href="{% url "day-detail" day.id%}" class="day-title">
                            <h3 class="day-text">Day: {{day.day}}</h3>
                            <h4 class="day-text">{{day.date}}</h4>
                            {% comment %} {% if day.start_location or day.finish_location %}
                                <h5>{{day.start_location}} ➤ {{day.finish_location}}</h5>
                            {% else %}
                                <h5> Edit Day to Set Location</h5>
                            {% endif %} {% endcomment %}
                            <h6>Notes: {{day.note_set.count }}</h6>
                            {% comment %} <img  class="icon-img" src="{% static "images/write.svg" %}" alt="edit icon"> {% endcomment %}
                        
                    </a>
            </div>
            {% endfor %}
        </div>

        <div class="feature-two-container">
            <div class="subsection-title">
                <h2 class="subsection-title-text">Packing List</h2>
            </div>
            {% comment %} <a href="{% url "available-gear-index" trail.id%}">
                <h3>Available Gear</h3>
            </a> {% endcomment %}
            
            <div class="subsection-img" style="background-image: url('{% static "/images/tristan-pineda-LFGGCsj41Bc-unsplash.jpg" %}');">
                <div class="gear-container">
                {% if trail.gear.count %}

                    {% if all_packed %}
                    <h5>You're all set — no gear to pack right now!</h5>
                    {% endif %}

                    {% for gear in trail.gear.all %}
                    
                        {% if gear.packed == False %}

                            <form action="" method="post" autocomplete="off" class="packed-item">
                                {% csrf_token %}
                                <input type="checkbox" name="packed" value="True" 
                                    {% if gear.packed%} checked {% endif %}
                                    onchange="this.form.submit()"
                                >
                                <p >{{gear.name}}</p>
                                <input type="hidden" name="gear_id" value="{{gear.id}}">
                            </form>
                        {% endif %}
                    
                    {% endfor %}
                {% else %}
                <h5>To add Gear - click the gear details button above.</h5>
                {% endif %}
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock content %}

main_app/templates/trails/index.html
{% extends "base.html" %} {% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "css/trails/trail-index.css" %}">
{% endblock head %}

{% block content %}

<div class="container">
    
    <div class="header" >
        <h1 class="header-text">Oh, the Places You'll Go</h1>
    </div>

    <section class="section-header">
        <h2>{% if is_archive %}Archived trails {% else %} Upcoming Trails{% endif %}</h2>
            
            <div class="page-header-links">
                {% if is_archive %}
                <a href="{% url "trail-index" %}" class="page-links"><h5>Upcoming</h5></a>
                {% else %}
                <a href="{% url "trail-index" %}?view=archive" class="page-links"><h5>Archive</h5></a>
                {% endif %}
                <a href="{% url "trail-create" %}" class="page-links add"><h5>Add a New Adventure</h5></a>
            </div>
    </section>

    <section class="card-container">
        {% if trails.count %}

            {% for trail in trails %}
                <div class="card">
                    <a href="{% url "trail-detail" trail.id %}">

                        <div class="card-content">
                            <div class="card-img-container" >
                                <img class="card-img" src="{% static "images/" %}{{trail.image}}" alt="{{trail.name}}">
                            </div>
                            <div class="card-details">
                                <h4 class="card-title">{{trail.name}}</h4>
                                <h6>{{trail.start_date}} ➤ {{trail.end_date}}</h6>
                            </div>
                        </div>

                    </a>
                    
                </div>

            {% endfor %}
        {% else %}
        <h5>{% if is_archive %}No archived trails{% else %}No current Adventures planned{% endif %} </h5>

        {% endif %}
        
    </section>
</div>

{% endblock content %}